name: play
type: laravel
docroot: public
php_version: "8.5"
webserver_type: nginx-fpm
disable_settings_management: true
database:
  type: mariadb
  version: "11.8"
host_db_port: "32797"
timezone: UTC
nodejs_version: "24"
corepack_enable: true
hooks:
  post-start:
    - exec-host: ddev auth ssh
